"""
SQLAlchemy models matching the data model in the project brief:
documents, document_chunks, controls, investigations, findings,
finding_evidence, audit_events, review_feedback.

v1 scope: we persist investigations/findings/evidence links/audit events/
review feedback generated by the orchestrator. Document and chunk rows are
populated from the existing JSONL chunk store on first run (see session.py's
`sync_chunks_to_db`) rather than duplicating the ingestion pipeline.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, ForeignKey, Text, JSON
)
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


def _uid():
    return str(uuid.uuid4())


def _now():
    return datetime.now(timezone.utc)


class Document(Base):
    __tablename__ = "documents"
    id = Column(String, primary_key=True, default=_uid)
    filename = Column(String, nullable=False)
    document_type = Column(String)
    source_path = Column(String)
    checksum = Column(String)
    created_at = Column(DateTime, default=_now)

    chunks = relationship("DocumentChunk", back_populates="document")


class DocumentChunk(Base):
    __tablename__ = "document_chunks"
    id = Column(String, primary_key=True)  # reuse chunk_id from ingestion for stable joins
    document_id = Column(String, ForeignKey("documents.id"))
    section_or_row = Column(String)
    text = Column(Text)
    chunk_metadata = Column(JSON)

    document = relationship("Document", back_populates="chunks")


class Control(Base):
    __tablename__ = "controls"
    control_id = Column(String, primary_key=True)
    control_family = Column(String)
    name = Column(String)
    description = Column(Text)
    frequency = Column(String)
    criticality = Column(String)
    nist_csf_function = Column(String)


class Investigation(Base):
    __tablename__ = "investigations"
    id = Column(String, primary_key=True, default=_uid)
    title = Column(String)
    question = Column(Text)
    status = Column(String, default="open")  # open | closed
    created_by = Column(String)
    created_at = Column(DateTime, default=_now)

    findings = relationship("Finding", back_populates="investigation")


class Finding(Base):
    __tablename__ = "findings"
    id = Column(String, primary_key=True, default=_uid)
    investigation_id = Column(String, ForeignKey("investigations.id"))
    control_id = Column(String)
    risk_level = Column(String)
    risk_score = Column(Float)
    finding_text = Column(Text)
    evidence_status = Column(String)
    confidence = Column(Float)
    requires_human_review = Column(Boolean, default=True)
    status = Column(String, default="pending_review")  # pending_review | accepted | rejected | needs_more_evidence
    limitations = Column(Text)
    narrative_source = Column(String, default="template")  # template | llm | template-fallback-after-...
    created_at = Column(DateTime, default=_now)

    investigation = relationship("Investigation", back_populates="findings")
    evidence = relationship("FindingEvidence", back_populates="finding")
    reviews = relationship("ReviewFeedback", back_populates="finding")


class FindingEvidence(Base):
    __tablename__ = "finding_evidence"
    id = Column(String, primary_key=True, default=_uid)
    finding_id = Column(String, ForeignKey("findings.id"))
    chunk_id = Column(String)
    document_name = Column(String)
    quote = Column(Text)
    relevance_score = Column(Float)

    finding = relationship("Finding", back_populates="evidence")


class ReviewFeedback(Base):
    __tablename__ = "review_feedback"
    id = Column(String, primary_key=True, default=_uid)
    finding_id = Column(String, ForeignKey("findings.id"))
    reviewer = Column(String)
    decision = Column(String)  # accept | reject | request_evidence
    comment = Column(Text)
    timestamp = Column(DateTime, default=_now)

    finding = relationship("Finding", back_populates="reviews")


class AuditEvent(Base):
    __tablename__ = "audit_events"
    id = Column(String, primary_key=True, default=_uid)
    event_type = Column(String)  # investigation_created | finding_created | review_submitted
    user_id = Column(String)
    investigation_id = Column(String, nullable=True)
    finding_id = Column(String, nullable=True)
    model_version = Column(String, default="orchestrator-v1-rule-based")
    detail = Column(JSON)
    timestamp = Column(DateTime, default=_now)
